rvm:
- 1.9.3
- 2.0.0
- 2.1
- 2.2

sudo: true

env:
  matrix:
# CHEF_VERSION is only for unit tests, no for test-kitchen:
  - TESTS="style unit" CHEF_VERSION="~> 11.0"
  - TESTS="style unit" CHEF_VERSION="~> 12.0"
# Split up the test-kitchen run to avoid exceeding 50 minutes:
  - TESTS="integration[attrs-centos-6]"
  - TESTS="integration[attrs-debian-6]"
  - TESTS="integration[attrs-debian-7]"
  - TESTS="integration[attrs-debian-8]"
  - TESTS="integration[attrs-ubuntu-1204]"
  - TESTS="integration[attrs-ubuntu-1404]"
  - TESTS="integration[attrs-ubuntu-1410]"
  - TESTS="integration[attrs-ubuntu-1504]"
  - TESTS="integration[attrs-centos-7]"

matrix:
  exclude:
# Chef 12 requires Ruby 2:
  - rvm: 1.9.3
    env: TESTS="style unit" CHEF_VERSION="~> 12.0"
# Chef 11 cannot resolve dependencies in Ruby 2.2 (mixlib-shellout):
  - rvm: 2.2
    env: TESTS="style unit" CHEF_VERSION="~> 11.0"
# Disable integration tests in old Ruby versions:
  - rvm: 1.9.3
    env: TESTS="integration[attrs-centos-6]"
  - rvm: 2.0.0
    env: TESTS="integration[attrs-centos-6]"
  - rvm: 2.1
    env: TESTS="integration[attrs-centos-6]"
  - rvm: 1.9.3
    env: TESTS="integration[attrs-debian-6]"
  - rvm: 2.0.0
    env: TESTS="integration[attrs-debian-6]"
  - rvm: 2.1
    env: TESTS="integration[attrs-debian-6]"
  - rvm: 1.9.3
    env: TESTS="integration[attrs-debian-7]"
  - rvm: 2.0.0
    env: TESTS="integration[attrs-debian-7]"
  - rvm: 2.1
    env: TESTS="integration[attrs-debian-7]"
  - rvm: 1.9.3
    env: TESTS="integration[attrs-debian-8]"
  - rvm: 2.0.0
    env: TESTS="integration[attrs-debian-8]"
  - rvm: 2.1
    env: TESTS="integration[attrs-debian-8]"
  - rvm: 1.9.3
    env: TESTS="integration[attrs-ubuntu-1204]"
  - rvm: 2.0.0
    env: TESTS="integration[attrs-ubuntu-1204]"
  - rvm: 2.1
    env: TESTS="integration[attrs-ubuntu-1204]"
  - rvm: 1.9.3
    env: TESTS="integration[attrs-ubuntu-1404]"
  - rvm: 2.0.0
    env: TESTS="integration[attrs-ubuntu-1404]"
  - rvm: 2.1
    env: TESTS="integration[attrs-ubuntu-1404]"
  - rvm: 1.9.3
    env: TESTS="integration[attrs-ubuntu-1410]"
  - rvm: 2.0.0
    env: TESTS="integration[attrs-ubuntu-1410]"
  - rvm: 2.1
    env: TESTS="integration[attrs-ubuntu-1410]"
  - rvm: 1.9.3
    env: TESTS="integration[attrs-ubuntu-1504]"
  - rvm: 2.0.0
    env: TESTS="integration[attrs-ubuntu-1504]"
  - rvm: 2.1
    env: TESTS="integration[attrs-ubuntu-1504]"
  - rvm: 1.9.3
    env: TESTS="integration[attrs-centos-7]"
  - rvm: 2.0.0
    env: TESTS="integration[attrs-centos-7]"
  - rvm: 2.1
    env: TESTS="integration[attrs-centos-7]"

bundler_args: --jobs=3 --retry=3 --without='doc integration_vagrant integration_cloud guard'

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.3.0/scripts/start_docker.sh)

script:
- travis_retry bundle exec rake $TESTS

after_failure: cat docker_daemon.log
